
# version: '3'

# services:
#   node-server:
#     container_name: node
#     build: .
#     ports:
#       - "8081:8081"
#     depends_on:
#       - db
#     links:
#       - db
#     volumes:
#       - ./prisma:/usr/src/app/prisma
#        - './.env:/usr/src/app/.env'
#     env_file:
#       - .env
#     environment:
#       DATABASE_URL: "mysql://root:root@db:3306/db"

#   db:
#     image: mysql:latest
#     hostname: db
#     container_name: db
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: db
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data_test:/var/lib/mysql

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: phpmyadmin
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_USER: root
#       PMA_PASSWORD: root
#     ports:
#       - "8080:80"
#     depends_on:
#       - db

#   prisma:
#     container_name: prisma
#     build: .
#     command: npx prisma generate
#     volumes:
#       - ./prisma:/use/src/app/prisma # Mount the prisma directory
#     environment:
#       DATABASE_URL: "mysql://root:root@db:3306/project"

# volumes:
#   mysql_data_test:





version: '3'

services:
  node-server:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./.env:/usr/src/app/.env
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/db"
  
  python-api:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - "5000:5000"
    volumes:
      - ./model:/usr/src/app/model
    depends_on:
      - db

  db:
    image: mysql:latest
    hostname: db
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data_test:

networks:
  default:


