# Dockerfile-python
FROM python:3.8

WORKDIR /usr/src/app

# Install Flask, Gunicorn, scikit-learn (specific version), joblib
RUN pip install Flask gunicorn scikit-learn==1.3.1 joblib

COPY model/kmeans_model.joblib /usr/src/app/
COPY model.py /usr/src/app/

EXPOSE 5000

# Replace 'app' with the actual variable name of your Flask app inside model.py if it's different
CMD ["gunicorn", "-b", "0.0.0.0:5000", "model:app"]
